name: mobile
description: Anna mobile application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.4
  flutter_spinkit: ^5.0.0
  cupertino_icons: ^1.0.2
  cloud_firestore: ^1.0.6
  get_it: ^6.1.1
  rxdart: ^0.26.0
  firebase_storage: ^8.0.4
  image_picker: ^0.7.5
  hexcolor: ^2.0.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
