CREATE TABLE Ta(
	aid INT PRIMARY KEY IDENTITY(0, 1),
	a1 VARCHAR(30) NOT NULL,
	a2 INT UNIQUE
);

CREATE TABLE Tb(
	bid INT PRIMARY KEY IDENTITY(0, 1),
	b1 VARCHAR(40) NOT NULL,
	b2 INT
);

CREATE TABLE Tc(
	cid INT PRIMARY KEY IDENTITY(0, 1),
	aid INT FOREIGN KEY REFERENCES Ta(aid),
	bid INT FOREIGN KEY REFERENCES Tb(bid)
);