test: test.cpp implementations/*
	g++ -std=c++11 -Wall -Werror -Wfatal-errors -o test test.cpp implementations/graph_iterator.cpp implementations/graph.cpp implementations/vertex_iterator.cpp implementations/vertex.cpp
	./test
	rm ./test
