test:
	g++ -std=c++11 -g -Wall -Werror -Wfatal-errors -o test \
test.cpp implementations/graph.cpp implementations/vertex.cpp \
implementations/iterator.cpp implementations/generator.cpp
	./test
	rm ./test
