CREATE TABLE Deliveries(
	DeliveryId INT PRIMARY KEY,
	DriverId CHAR(8) FOREIGN KEY REFERENCES Users(IdentityDocument) NOT NULL,
	StartAddress VARCHAR(50) NOT NULL,
	EndAddress VARCHAR(50) NOT NULL,
	Fare FLOAT NOT NULL,
	VehicleId INT FOREIGN KEY REFERENCES Vehicles(VehicleId) NOT NULL,
);