export const UPDATE_CONTEXT_PROPOSAL = 'UPDATE_CURRENT_PROPOSAL';
export const UPDATE_CONTEXT_REVIEW = 'UPDATE_CURRENT_REVIEW';
export const RESET_CONTEXT_PROPOSAL = 'RESET_CONTEXT_PROPOSAL';
export const UPDATE_CONTEXT_CONFERENCE = 'UPDATE_CONTEXT_CONFERENCE';
